---

- name: 复制mariadb repository
  copy:
    src: repo-latest
    dest: /etc/yum.repos.d/mariadb.repo


- name: 安装mariadb
  yum:
    name: mariadb-server
    state: installed


- name: 启动mariadb
  service:
    name: mariadb
    state: started
