---

- name: 安装nginx
  yum:
    name: nginx
    state: installed


- name: 复制nginx的systemd配置文件
  copy:
    src: systemd-nginx.service
    dest: /usr/lib/systemd/system/nginx.service


- name: 启动nginx
  systemd:
    daemon_reload: yes
    state: restarted
    name: nginx
