---

- name: 添加mongodb repository
  copy:
    src: repo-3.4
    dest: /etc/yum.repos.d/mongodb-org-3.4.repo


- name: 安装mongodb
  yum:
    name: mongodb-org
    state: installed


- name: 启动mongodb
  service:
    name: mongod
    state: started
